# Generated by Django 2.0.6 on 2018-06-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0006_auto_20180619_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='altchar',
            name='sequence_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='altchar',
            name='source_obj',
            field=models.CharField(default='', max_length=255),
        ),
    ]
