# Generated by Django 2.0.6 on 2018-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0007_auto_20180620_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='name',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
