# Generated by Django 2.0.6 on 2018-08-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0008_auto_20180625_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altchar',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='char',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='charinsource',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='altchar',
            old_name='location',
            new_name='source',
        ),
    ]
