# Generated by Django 2.0.6 on 2018-08-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0009_auto_20180808_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='altchar',
            unique_together={('canonical', 'sequence_no', 'page', 'source', 'name')},
        ),
    ]
