# Generated by Django 2.1.2 on 2018-11-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0010_auto_20180808_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altchar',
            options={'ordering': ['id']},
        ),
    ]
